Repository phoenix-team4/phoenix-team4, pull requests merged in 2023-06, with the labels that each got.

#8 [dev](utils): utils 추가
  src/scss/utils/_a11y.scss
  src/scss/utils/_color.scss
  src/scss/utils/_flexbox.scss
  src/scss/utils/_index.scss
  src/scss/utils/_media-query.scss
  src/scss/utils/_mixin.scss
  src/scss/utils/_unit.scss
Labels: dev

#11 [dev](header) : index - header 추가
  package-lock.json
  src/images/main-banner.png
  src/images/tving-icon.png
  src/index.html
  src/views/header.html
Labels: dev

#12 [dev](content2): content 내용 추가
  src/index.html
  src/views/content.html
Labels: dev

#14 [dev](only): 오직 티빙에만 마크업 및 index.html 추가
  .DS_Store
  src/.DS_Store
  src/images/.DS_Store
  src/index.html
  src/views/only.html
Labels: dev

#15 [dev](event) : event markup 완성
  src/images/event-sprite.svg
  src/images/event-sprites.png
  src/index.html
  src/views/event.html
Labels: dev

#16 [dev](footer2): 푸터 마크업 및 index.html 추가
  src/index.html
Labels: dev

#17 [upd] (favorite):
  src/scss/utils/_color.scss
Labels: update

#23 [dev](content2): 콘텐츠 및 quick 섹션 완료
  .DS_Store
  src/.DS_Store
  src/images/.DS_Store
  src/images/content/괴이.png
  src/images/content/러브캐처인발리.png
  src/images/content/몸값.png
  src/images/content/술꾼도시여자들.png
  src/images/content/전체관람가.png
  src/images/content/푸드크로니클.png
  src/images/content/환승연애2.png
  src/images/quick/F_webp400.svg
  src/images/quick/건강면세점.svg
  src/images/quick/나는살기로했다.svg
  src/images/quick/알맹이.svg
  src/images/quick/엄마의봄날.svg
  src/images/quick/차이나는클라스.svg
  src/index.html
  src/scss/pages/_content.scss
  src/style/index.css
  src/style/index.css.map
Labels: dev, update

#19 [upd] (favorite): favorite div.infoWrapper 추가, img 태그 추가
  src/images/favorite_live.png
  src/images/favorite_program.png
  src/images/live/JTBC.svg
  src/images/live/NewsTV.svg
  src/images/live/YTN.svg
  src/images/live/animation.svg
  src/images/live/drama.svg
  src/images/live/tvN.svg
  src/images/program/program_1.svg
  src/images/program/program_2.svg
  src/images/program/program_3.svg
  src/images/program/program_4.svg
  src/images/program/program_5.svg
  src/images/program/program_6.svg
  src/images/program/program_7.svg
  src/images/program/program_8.svg
  src/images/ranking.png
  src/images/ranking/ranking1.svg
  src/images/ranking/ranking2.svg
  src/images/ranking/ranking3.svg
  src/images/ranking/ranking4.svg
  src/images/ranking/ranking5.svg
  src/images/ranking/ranking6.svg
  src/images/ranking/ranking7.svg
  src/images/ranking/ranking8.svg
  src/index.html
  src/scss/pages/_favorite.scss
  src/style/index.css
  src/style/index.css.map
  src/views/favorite.html
Labels: dev, update, delete

#24 [dev](only): 오직 티빙에만 sass 스타일 완성
  .DS_Store
  src/.DS_Store
  src/images/only-poster01.svg
  src/images/only-poster02.svg
  src/images/only-poster03.svg
  src/images/only-poster04.svg
  src/images/only-poster05.svg
  src/images/only-poster06.svg
  src/images/only-poster07.svg
  src/images/sports.svg
  src/index.html
  src/scss/pages/_only.scss
  src/style/index.css
  src/style/index.css.map
Labels: dev

#25 [upd](footer): 충돌 병합 수정 및 views 폴더 html파일 삭제
  .DS_Store
  src/.DS_Store
  src/images/facebook.svg
  src/images/instagram.svg
  src/images/sports.svg
  src/images/twitter.svg
  src/images/youtube.svg
  src/index.html
  src/scss/layout/_footer.scss
  src/scss/layout/_header.scss
  src/style/index.css
  src/style/index.css.map
  src/views/content.html
  src/views/event.html
  src/views/favorite.html
  src/views/header.html
  src/views/only.html
Labels: dev, update

#31 Header
  src/images/banner-img.png
  src/images/event-6.png
  src/images/tving-logo-icon.png
  src/index.html
  src/scss/layout/_event.scss
  src/scss/layout/_header.scss
  src/scss/pages/_content.scss
  src/style/index.css
  src/style/index.css.map
Labels: dev, update

#28 [upd](only): adBanner img태그 src 수정 및 sports.svg 파일 수정
  src/images/sports.svg
  src/index.html
Labels: update

#29 [upd](footer): footer 태그 수정
  src/index.html
Labels: update

#30 [upd][dev] (login): index.html에 login.html 추가 / login 마크업 완료
  src/images/Input.svg
  src/images/Property 1=login, Property 2=id.svg
  src/images/checked.svg
  src/images/uncheck.svg
  src/images/viewing.svg
  src/scss/pages/_index.scss
  src/scss/pages/_login.scss
  src/style/index.css
  src/style/index.css.map
  src/views/login.html
Labels: dev, update

#32 [upd](content2): 콘텐츠 및 quick 섹션 수정 완료
  src/index.html
  src/scss/pages/_content.scss
  src/style/index.css
  src/style/index.css.map
Labels: update

#33 [upd][del] (login): 로그인 마크업 수정 / scss 수정 / 이미지 삭제
  src/images/favorite.png
  src/scss/pages/_login.scss
  src/style/index.css
  src/style/index.css.map
Labels: update, delete

#34 [dev](header) : header 수정 , event.sass 추가
  src/index.html
  src/scss/layout/_event.scss
  src/scss/layout/_header.scss
  src/style/index.css
  src/style/index.css.map
Labels: dev, update

#35 [udp](header): header.scss 수정
  src/scss/layout/_header.scss
  src/scss/pages/_findpw.scss
  src/scss/pages/_index.scss
  src/style/index.css.map
  src/views/findpw.html
Labels: update

#39 [upd](footer): footer html img 태그 경로 수정 및 scss 수정
  src/index.html
  src/scss/layout/_footer.scss
  src/style/index.css
  src/style/index.css.map
  src/style/signup.css
  src/style/signup.css.map
Labels: update

#41 [dev](findpw) : markup 완성 , sass 완성
  src/scss/pages/_findpw.scss
  src/style/index.css
  src/style/index.css.map
  src/views/findpw.html
Labels: dev, update

#43 [merge](login): 변경사항 반영
  src/scss/pages/_login.scss
  src/style/index.css
  src/style/index.css.map
  src/views/login.html
Labels: update

#45 [upd](findId): 헤더 마크업 수정, button a태그로 변경, input color 변경
  src/scss/pages/_content.scss
  src/scss/pages/_find-id.scss
  src/style/index.css
  src/style/index.css.map
  src/views/find-id.html
Labels: update

#46 [upd / merge](login): 로그인 페이지 링크연결 및 버튼 위치이동
  src/scss/pages/_login.scss
  src/style/index.css
  src/style/index.css.map
  src/views/login.html
Labels: update

#47 [upd](only): h2 태그 폰트사이즈 변경
  src/scss/pages/_only.scss
Labels: update

#49 [upd](content): 빨간 박스 height 제거, 메인 페이지 글자 크기 조정, 콘텐츠 이미지 오버플로우
  src/scss/pages/_content.scss
  src/style/index.css
  src/style/index.css.map
Labels: update

#50 [upd](signup): input color, 여백 스타일링 수정
  src/scss/pages/_signup.scss
  src/style/index.css
  src/style/index.css.map
  src/views/signup.html
Labels: update

#54 [upd](signup): header svg 수정
  src/views/signup.html
Labels: update

#57 [upd](findId): 태블릿, 모바일 버전에서 타이틀에 margin-top 넣음
  src/scss/pages/_find-id.scss
  src/style/index.css
Labels: update

#60 [upd](only): index.html 수정
  src/index.html
Labels: update

#61 [dev](findpw) : img 자세히보기 완성
  src/index.html
  src/scss/layout/_header.scss
  src/scss/pages/_findpw.scss
  src/style/index.css
  src/style/index.css.map
Labels: dev

#62 [dev](findpw) : header sass 추가
  src/scss/pages/_findpw.scss
  src/style/index.css
  src/style/index.css.map
Labels: update

#63 [upd](signup): 체크 글자색 및 푸터 마크업 수정
  src/scss/pages/_signup.scss
  src/style/index.css
  src/style/index.css.map
  src/views/signup.html
Labels: update

#64 [upd](findId): 폰트 적용
  src/views/find-id.html
Labels: update

#65 [dev](findpw) : 폰트수정, alt 수정
  src/index.html
  src/views/findpw.html
Labels: update

#66 [upd](login):'로그인 페이지 폰트 적용'
  src/views/login.html
Labels: update
